name: Deploy Frontend UI

on:
  push:
    branches:
      - master # Ubah ke 'master' jika branch utama Anda bernama master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # 1. Pindah ke direktori proyek (UBAH SESUAI REPOSITORY)
            cd /var/www/html/solher-frontend
            c
            # 2. Tarik update terbaru
            git pull
            
            # 3. Update NPM (hanya jika ada tambahan package baru)
            # npm install
            
            # 4. Compile ulang aset Frontend
            npm run build